from factories import *

FACTORY_BRICKS = Factory('bricks', FACTORY_BRICK_CONTRACT, 0)
FACTORY_CONCRETE = Factory('concrete', FACTORY_CONCRETE_CONTRACT, 0)
FACTORY_FUEL = Factory('fuel', FACTORY_FUEL_CONTRACT, 0)
FACTORY_COPPER = Factory('copper', FACTORY_COPPER_CONTRACT, 0)
FACTORY_ALUMINUM = Factory('aluminum', FACTORY_ALUMINUM_CONTRACT, 0)
FACTORY_MEDTECH = Factory('medtech', FACTORY_MEDTECH_CONTRACT, 0)
FACTORY_STEEL = Factory('steel', FACTORY_STEEL_CONTRACT, 0)
FACTORY_GLASS = Factory('glass', FACTORY_GLASS_CONTRACT, 0)
FACTORY_INSECTICIDE = Factory('insecticide', FACTORY_INSECTICIDE_CONTRACT, 0)
FACTORY_PLASTIC = Factory('plastic', FACTORY_PLASTIC_CONTRACT, 0)
FACTORY_LITHIUM = Factory('lithium', FACTORY_LITHIUM_CONTRACT, 0)
FACTORY_ACCUMULATOR = Factory('accumulator', FACTORY_ACCUMULATOR_CONTRACT, 0)
FACTORY_WEAPONS = Factory('weapons', FACTORY_WEAPONS_CONTRACT, 0)
FACTORY_SILICON = Factory('silicon', FACTORY_SILICON_CONTRACT, 0)
FACTORY_CIRCUITRY = Factory('circuitry', FACTORY_CIRCUITRY_CONTRACT, 0)
FACTORY_TITANIUM = Factory('titanium', FACTORY_TITANIUM_CONTRACT, 0)
FACTORY_SILVER = Factory('silver', FACTORY_SILVER_CONTRACT, 0)
FACTORY_GOLD = Factory('gold', FACTORY_GOLD_CONTRACT, 0)
FACTORY_FERTILIZER = Factory('fertilizer', FACTORY_FERTILIZER_CONTRACT, 0)
FACTORY_TRUCKS = Factory('trucks', FACTORY_TRUCKS_CONTRACT, 0)
FACTORY_DRONE = Factory('drone', FACTORY_DRONE_CONTRACT, 0)
FACTORY_JEWELLERY = Factory('jewellery', FACTORY_JEWELLERY_CONTRACT, 0)

factories = [
    FACTORY_CONCRETE,
    FACTORY_BRICKS,
    FACTORY_FUEL,
    FACTORY_COPPER,
    FACTORY_ALUMINUM,
    FACTORY_MEDTECH,
    FACTORY_STEEL,
    FACTORY_GLASS,
    FACTORY_INSECTICIDE,
    FACTORY_PLASTIC,
    FACTORY_LITHIUM,
    FACTORY_ACCUMULATOR,
    FACTORY_WEAPONS,
    FACTORY_SILICON,
    FACTORY_CIRCUITRY,
    FACTORY_TITANIUM,
    FACTORY_SILVER,
    FACTORY_GOLD,
    FACTORY_FERTILIZER,
    FACTORY_TRUCKS,
    FACTORY_DRONE,
    FACTORY_JEWELLERY,
]

for s in topNforUpgrade(factories, int(input("Топ сколько показать?"))):
    print(s)